version: '3.4'

services:

  eureka-server: 
    image: pedrobittencourtcosta/eureka-service:1.0.0
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - micro-services
      
  user-api:
    image: pedrobittencourtcosta/user-api:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - micro-services

networks:
  micro-services:
    driver: bridge